version: '2'
services:

  cassandra-seed1:
    image: cassandra
    container_name: cassandra-seed1
    hostname: cassandra-seed1
    restart: always
    ports:
      - "9042:9042"
    networks:
      service_network:
        ipv4_address: 172.25.0.101

#  cassandra-node:
#    image: cassandra
#    restart: always
#    links:
#      - cassandra-seed1:seed1
#    environment:
#      - CASSANDRA_SEEDS=seed1
#    networks:
#      - service_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - service_network

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "user-interactions:5:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - service_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      service_network:
        ipv4_address: 172.25.0.100

networks:
  service_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24